//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnuProto
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LESSON()
        {
            this.STUDENT_PROG = new HashSet<STUDENT_PROG>();
        }
    
        public string L_NAME { get; set; }
        public string L_DESC { get; set; }
        public string L_CONTENT { get; set; }
        public int L_SECT { get; set; }
        public int L_ID { get; set; }
    
        public virtual SECTION SECTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_PROG> STUDENT_PROG { get; set; }
    }
}
